version: '3.8'

services:
  cashlink-api:
    build: .
    container_name: cashlink-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - /home/ubuntu/config/cashlink.env
